### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#1]
As a **user**, I can **sign up for an account** so that **I can access the app's content & features**.

### Acceptance Criteria
- Users should be able to easily navigate to the sign up form from the navbar. 
  - Sign Up option should only be available while logged out.
- The form should be intuitive, prompting the user to provide a username, password, and to confirm their password before submitting.
- Feedback should be given to the user if they provide invalid data in the form.
- Users should have the option to navigate to the log in page if they already have an account.

### Tasks
- [x] Create a sign up form
- [x] Create a sign-up route
- [x] Connect the backend to the frontend
- [x] Set up CurrentUserContext, display sign in nav link when user is logged out
- [x] Write js to handle the post request on form submission
- [x] Test that the form works by checking the drf-tasks api to confirm that a new profile has been created
