### ISSUE TITLE
USER STORY: Delete comments

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#16]
As an **authenticated user**, I can **delete my own comments** so that **I can remove them if they're no longer relevant**.

### Acceptance Criteria
- Users should be able to access a delete button from a dropdown menu on their own comments.
- Users should be prompted to confirm that they want to delete the comment before the request is submitted.

### Tasks
- [x]  Add dropdown menu component to the comments, render it to comment owners only
- [x]  Write js to handle the comment deletion request
- [x]  Add a modal for defensive programming
