### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#19]
As a **user**, I can **access a navbar** so that **I can easily navigate through the app**.

### Acceptance Criteria
- The navbar should be visible on all pages and responsive on different sized devices.
- Users should be able to log in or sign up if they are not already logged in.
- While authenticated, users should be able to access their tasks and profile from the navbar.

### Tasks
- [x] Create a navbar component
- [x] Add logo & navlinks
- [x] Create CurrentUserContext to display navlinks, define logged out & logged in navlinks
- [x] Style the navbar
