### ISSUE TITLE
USER STORY: Log In 

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#2]
As a **user**, I can **log in** so that **I can access the app’s content and features**.

### Acceptance Criteria
- Users should be able to easily navigate to the log in form from the navbar. 
  - Log In option should only be available while logged out.
- The form should be intuitive, prompting the user to provide a username & password before submitting.
- Feedback should be given to the user if they provide invalid data in the form.
- Users should have the option to navigate to the sign up page if they don't already have an account.

### Tasks
- [x] Create a log in form
- [x] Set up a log-in route
- [x] Ensure the backend is connected to the frontend
- [x] Set up CurrentUserContext, display log in nav link when user is logged out
- [x] Write js to handle the request on form submission
