### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#20]
As an **authenticated user**, I can **access user profiles** so that **I can learn more about the user**.

### Acceptance Criteria
- Users should be able to access profiles by clicking on profile pictures.
- The user's profile picture, username should be visible on the profile.
- Stats such as how many tasks the user has in progress/completed should be visible on the profile.

### Tasks
- [x] Set up ProfileDataContext
- [x] Fetch profile data from the API
- [x] Write jsx to render the data from the API

**Comment by akirby23** [comment]
Profile picture, user name as task count is displayed on the profile. To complete the profile, addional statistics will need to be added on the backed. This will be addressed on issue issue [14](https://github.com/akirby23/drf-tasked/issues/14).
