### ISSUE TITLE
USER STORY: 404 Error page

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#22]
As a **user**, I can **see an informative error page when faced with a 404 error** so that **I can understand if the page I'm looking for exists**.

### Acceptance Criteria
- The page should display when the user tries to access the page with an invalid url.

### Tasks
- [x] Add NotFound.js component
- [x] Add it to the Page Not Found route
- [x] Add new image to display on the 404 page
- [x] Add styling
