### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#3]
As an **authenticated user**, I can **log out** so that **I can protect my account**.

### Acceptance Criteria
- Users should be able to easily log out from the navbar. 
- Users should be prompted to confirm that they want to log out before the action is completed.
- Users should be redirected to the previous page if they decide to cancel.

### Tasks
- [x] Set up log out route
- [x] Add Log Out navlink for logged in users
- [x] Create a log out page for defensive programming
- [x] Write js to handle the log out/cancel log out requests
