### ISSUE TITLE
USER STORY: Create tasks

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#4]
As an **authenticated user**, I can **create a task** so that **I can manage & keep track of my responsibilities**.

### Acceptance Criteria
- A "Create Task" nav link should be visible to authenticated users. 
- Users should be navigated to a form that will allow them to create a new task once the nav link is clicked. 
- The form should be intuitive and allow users to add a title, category, priority level, task details & assignee. 

### Tasks
- [x] Create a CreateTaskForm component & route
- [x] Add state variables
- [x] Retrieve data from the backend
- [x] Add form submission handling logic
