### ISSUE TITLE
USER STORY: Retrieve tasks

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#6]
As an **authenticated user**, I can **retrieve my tasks** so that **I can access them to keep them up to date and/or make changes to them**.

### Acceptance Criteria
- Users should be able to access tasks in the form of a list from the nav bar.
- Task details such as the title, created date, updated date, category, priority level, assignee & status should be visible in the list view. 
- Users should be able to click on each task to open the datailed task view.

### Tasks
- [x] Create task page, task list & task components
- [x] Set up routes
- [x] Retrieve task data from the API
- [x] Write js to display the retrieved data
