### ISSUE TITLE
USER STORY: Delete tasks

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#7]
As an **authenticated user and task owner**, I can **delete my tasks** so that **I can remove them from my to-do list if they are no longer needed**.

### Acceptance Criteria
- Users should be able to access a delete button from a dropdown menu on their own tasks.
- Users should be prompted to confirm that they want to delete the task before the request is submitted.

### Tasks
- [x] Add dropdown menu component
- [x] Add delete button as a dropdown item
- [x] Write js to handle the task deletion request
- [x] Add a modal for defensive programming
