### ISSUE TITLE
USER STORY: Retrieve assigned tasks

### ISSUE THREAD

**Issue by akirby23** [akirby23/tasked#8]
As an **authenticated user**, I can **retrieve tasks that are assigned to me** so that **I can work on tasks that require action from me**.

### Acceptance Criteria
- Users should be able to access assigned tasks in the form of a list from the nav bar.
- Task details such as the title, created date, updated date, category, priority level, assignee & status should be visible in the list view. 
- Users should be able to click on each task to open the datailed task view.
- Only tasks that are assigned to the user should be visible.

### Tasks
- [x] Create task page, task list & task components
- [x] Set up routes
- [x] Retrieve task data from the API, add filter to the route
- [x] Write js to display the retrieved data
